#!/usr/bin/env bash

# shamelessly ripped from nathforge @ github: https://gist.github.com/nathforge/7120225

SUBLIME_CACHE=~/sublime_cache
SUBLIME_COMMAND="/c/Toolz/Sublime\ Text/subl"

# Allow piping to Sublime Text. Doesn't interfere with normal use.

if test "$1" == "--desktop"; then
	eval $SUBLIME_COMMAND
elif test -t 0; then
	# Is stdin a terminal?
	# Stdin is a terminal.
	# Open sublime normally.
	eval $SUBLIME_COMMAND "$@"
else
	# Stdin is not a terminal, it must be a pipe.
	# Pipe stdin to a temporary file, and open it in sublime.
	FILENAME=$(mktemp -p $SUBLIME_CACHE)
	cat >"$FILENAME" && eval "$SUBLIME_COMMAND $@ $FILENAME"
fi
